name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'    

permissions:
  contents: read
  id-token: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      static: ${{ steps.filter.outputs.static }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for file changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            static:
              - 'app/static/**'
            app:
              - 'app/backend/**'
              

  deploy-app:
    needs: check-changes
    if: needs.check-changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-south-1
      ECS_CLUSTER: dev-cluster
      ECS_SERVICE: dev-service
      ECS_TASK_FAMILY: dev-task
      CONTAINER_NAME: massar-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-deploy-app

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image URI
        run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/ecr-repository-dev" >> $GITHUB_ENV  

      - name: Build the Docker image
        run: docker build -t $IMAGE_URI:sha-${{ github.sha }} -t $IMAGE_URI:latest ./app/backend

      - name: Push the Docker image
        run: |
              docker push $IMAGE_URI:sha-${{ github.sha }} 
              docker push $IMAGE_URI:latest
          
      - name: Download active task definition
        run: |
              aws ecs describe-task-definition \
                --task-definition ${{ env.ECS_TASK_FAMILY }} \
                --query taskDefinition > task-definition.json
          
      - name: Render Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
              task-definition: task-definition.json
              container-name: ${{ env.CONTAINER_NAME }}
              image: ${{ env.IMAGE_URI }}:sha-${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  deploy-static:
    needs: check-changes
    if: needs.check-changes.outputs.static == 'true'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-south-1
      S3_BUCKET_NAME: dev-app-massar-static
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-deploy-static

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
         node-version: '20'

       - name: Install dependencies and build static files
         working-directory: ./app/static
         run : |
           npm ci
           npm run build

      - name: Upload static files to S3
        run: |
          aws s3 sync ./app/static s3://$S3_BUCKET_NAME/static/dist --delete --cache-control "no-cache"
          
      