name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'    

permissions:
  contents: read
  id-token: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      static: ${{ steps.filter.outputs.static }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for file changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            static:
              - 'app/static/**'
            app:
              - 'app/backend/**'
              

  deploy-app:
    needs: check-changes
    if: needs.check-changes.outputs.app == 'true'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-south-1
      ECS_CLUSTER: dev-cluster
      ECS_SERVICE: dev-service
      ECS_TASK_FAMILY: dev-task
      CONTAINER_NAME: massar-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-deploy-app

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image URI
        run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/ecr-repository-dev" >> $GITHUB_ENV  

      - name: Build the Docker image
        run: docker build -t $IMAGE_URI:sha-${{ github.sha }} -t $IMAGE_URI:latest ./app/backend

      - name: Push the Docker image
        run: |
              docker push $IMAGE_URI:sha-${{ github.sha }} 
              docker push $IMAGE_URI:latest
          
      - name: Download active task definition
        run: |
              aws ecs describe-task-definition \
                --task-definition ${{ env.ECS_TASK_FAMILY }} \
                --query taskDefinition > task-definition.json
          
      - name: Render Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
              task-definition: task-definition.json
              container-name: ${{ env.CONTAINER_NAME }}
              image: ${{ env.IMAGE_URI }}:sha-${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

  deploy-static:
    needs: check-changes
    if: needs.check-changes.outputs.static == 'true'
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-south-1
      S3_BUCKET_NAME: dev-app-massar-static
      ENVIRONMENT: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-deploy-static

      - name: export the cognito environment variables from ssm 
        run: |
          echo "VITE_COGNITO_USER_POOL_ID=$(aws ssm get-parameter --name '/massar/${{ env.ENVIRONMENT }}/cognito_user_pool_id' --query 'Parameter.Value' --output text)" >> $GITHUB_ENV
          echo "VITE_COGNITO_CLIENT_ID=$(aws ssm get-parameter --name '/massar/${{ env.ENVIRONMENT }}/cognito_client_id' --query 'Parameter.Value' --output text)" >> $GITHUB_ENV    

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
         node-version: '24'
         cache: 'npm' # Cache npm dependencies to speed up subsequent builds

      - name: Install dependencies and build static files
        working-directory: ./app/static
        run: |
          npm ci
          npm run build

      - name: Upload static files to S3
        run: |
          # 1. Upload all hashed assets by vite (JS, CSS) with 1-year cache
          aws s3 sync ./app/static/dist s3://$S3_BUCKET_NAME/static --delete \
            --exclude "*.html" \
            --cache-control "max-age=31536000, public, immutable" 

          # 2. Upload HTML files with no-cache to ensure they are always fresh
          aws s3 sync ./app/static/dist s3://$S3_BUCKET_NAME/static \
            --exclude "*" \
            --include "*.html" \
            --cache-control "no-cache, no-store, must-revalidate" 
            